# Generated by Django 3.2.9 on 2021-11-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211121_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storecategory',
            old_name='categoryName',
            new_name='category_Name',
        ),
    ]
